### ISSUE TITLE
Miss hid report when the application window is not focused

### ISSUE THREAD

**Issue by alex4me** [Slion/SharpLibHid#8]
After switching to another applictaion, the hook method does not respose to the report due to the fact that the Handle in RAWINPUTDEVICE is a handle of current process.Is there any method to globally hook hid report?
Thanks.

**Comment by Slion** [comment]
You have to use RIDEV_INPUTSINK or RIDEV_EXINPUTSINK depending of what you need:
See:  https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-rawinputdevice
